name: SonarQube Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar .NET 8
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Instalar SonarScanner para .NET
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # Iniciar análisis
      - name: Begin SonarQube analysis
        run: dotnet-sonarscanner begin /k:"RecocycleProyectos1" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      # Compilar tu proyecto
      - name: Build project
        run: dotnet build Web_Recocycle.sln --configuration Release

      # Finalizar análisis
      - name: End SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
